language: rust

cache:
  cargo: true

dist: trusty
sudo: false

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - ./install_cargo_web.sh
  - cargo web build --release --target=wasm32-unknown-unknown
